FROM openjdk:17-alpine

WORKDIR /app

COPY target/AircraftOrdnanceManagementSystem-0.0.1-SNAPSHOT.jar .

EXPOSE 8082

ENTRYPOINT ["java","-jar","AircraftOrdnanceManagementSystem-0.0.1-SNAPSHOT.jar"]