FROM openjdk:17-alpine

WORKDIR /app

COPY target/MilitaryAirBaseManagementSystem-0.0.1-SNAPSHOT.jar .

EXPOSE 8081

ENTRYPOINT ["java","-jar","MilitaryAirBaseManagementSystem-0.0.1-SNAPSHOT.jar"]